services:
  - type: web
    name: cobranzas-surqui
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
